### ISSUE TITLE
White results

### ISSUE THREAD

**Issue by AidasK** [yingcong/Facelet_Bank#2]
Hi, I have tried all the examples with all the models and different strengths, but all results are the same. What might be wrong? 
Result images are attached:
input-facehair-s-1:
![input-facehair-s-1](https://user-images.githubusercontent.com/2088484/41087733-102763ac-6a46-11e8-9ca8-c081f6ec426f.png)
input-younger-s-5:
![input-younger-s-5](https://user-images.githubusercontent.com/2088484/41087739-14799c72-6a46-11e8-8068-2c86806e9393.png)

**Comment by yingcong** [comment]
Hi @AidasK . I cannot reproduce this in my machine. But I guess it might be because of the wrong image range. In 
https://github.com/yingcong/Facelet_Bank/blob/0d0fbd88ac9175f6c6f62e439a4875a3979da58a/data/testData.py#L36
"img" is supposed to range from 0 to 1. But maybe in some version of imageio its range is [0,255].
To identify the problem, could you change 
img = imageio.imread(self.files[index]).astype(np.float32)
to 
img = imageio.imread(self.files[index]).astype(np.float32) / 255. 
to see if the result is correct?

**Comment by AidasK** [comment]
Right on spot! It works and results are awesome. Thanks :)

**Comment by MdAshrafulAlam** [comment]
@AidasK May I have your kind attention. Please.....

**Comment by MdAshrafulAlam** [comment]
@AidasK May I have your kind attention? Please.....
